### ISSUE TITLE
reduce resize duration for each frame 

### ISSUE THREAD

**Issue by fajrifernanda** [willnorris/gifresize#4]
is it possible to reduce resize duration by using goroutines for processing each frame? but it will affect cpu/memory usage

**Comment by willnorris** [comment]
that's a great idea... yeah, that should be totally possible.  We'd need to make sure that the frames get reassembled in the right order, but that shouldn't be too difficult.  

I probably won't have time to try this myself for a little while, but if you want to give it a shot, I'd be happy to assign the issue to you.  Otherwise, we can just leave it open for now.

**Comment by willnorris** [comment]
Looking at this more closely, I don't think we can process frames in parallel.  The way gif disposal methods work, each frame potentially needs access to the previous processed frame, so they have to be handled sequentially.

I'm going to go ahead and close this, since I don't think it's possible, but please feel free to reopen if an alternative comes to mind.
